###################################################################

# Created by write_sdc on Mon Jul 27 17:59:55 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current uA
set_max_area 0
create_clock [get_ports clk]  -period 10  -waveform {0 5}
set_clock_uncertainty -setup 0.5  [get_clocks clk]
set_clock_uncertainty -hold 0.1  [get_clocks clk]
set_input_delay -clock clk  2  [get_ports rst_n]
set_output_delay -clock clk  2  [get_ports {pc_debug[31]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[30]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[29]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[28]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[27]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[26]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[25]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[24]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[23]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[22]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[21]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[20]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[19]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[18]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[17]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[16]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[15]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[14]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[13]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[12]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[11]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[10]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[9]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[8]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[7]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[6]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[5]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[4]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[3]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[2]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[1]}]
set_output_delay -clock clk  2  [get_ports {pc_debug[0]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[31]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[30]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[29]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[28]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[27]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[26]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[25]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[24]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[23]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[22]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[21]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[20]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[19]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[18]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[17]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[16]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[15]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[14]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[13]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[12]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[11]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[10]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[9]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[8]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[7]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[6]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[5]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[4]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[3]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[2]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[1]}]
set_output_delay -clock clk  2  [get_ports {alu_debug[0]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[31]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[30]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[29]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[28]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[27]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[26]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[25]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[24]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[23]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[22]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[21]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[20]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[19]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[18]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[17]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[16]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[15]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[14]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[13]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[12]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[11]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[10]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[9]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[8]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[7]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[6]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[5]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[4]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[3]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[2]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[1]}]
set_output_delay -clock clk  2  [get_ports {wb_data_debug[0]}]
